FROM bitnami/mongodb:4.0-ol-7

ENV MONGODB_USERNAME=is
ENV MONGODB_PASSWORD=is_dev
ENV MONGODB_DATABASE=glogger_form
ENV MONGODB_DATABASE=glogger_form
ENV GOOGLE_CLIENT_ID=193585639610-mrvoo6dbq3i00gm9jmlhf3nship9h89s.apps.googleusercontent.com
ENV GOOGLE_CLIENT_SECRET=193585639610-mrvoo6dbq3i00gm9jmlhf3nship9h89s.apps.googleusercontent.com,
ENV MONGO_URI=mongodb://is:is_dev@localhost:27017/admin,
ENV COOKIE_KEY=asdjansjkfndfkjsdmfmwodrwpeodaskdfkmdsfwerofmwoewenfuwenfuwefnuwefnweufn,

VOLUME /bitnami

EXPOSE 27017